Index: .idea/workspace.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+><?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<project version=\"4\">\r\n  <component name=\"ProjectViewState\">\r\n    <option name=\"hideEmptyMiddlePackages\" value=\"true\" />\r\n    <option name=\"showLibraryContents\" value=\"true\" />\r\n  </component>\r\n  <component name=\"PropertiesComponent\">{\r\n  &quot;keyToString&quot;: {\r\n    &quot;last_opened_file_path&quot;: &quot;C:/Users/stian/Documents&quot;\r\n  }\r\n}</component>\r\n</project>
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.idea/workspace.xml b/.idea/workspace.xml
--- a/.idea/workspace.xml	(revision 27adf916a822967d46e2f667e4c1aad320e8d14e)
+++ b/.idea/workspace.xml	(date 1696683081117)
@@ -9,4 +9,24 @@
     &quot;last_opened_file_path&quot;: &quot;C:/Users/stian/Documents&quot;
   }
 }</component>
+  <component name="RunManager">
+    <configuration name="PopulateTestData$VotingAppMain" type="Application" factoryName="Application" temporary="true" nameIsGenerated="true">
+      <option name="MAIN_CLASS_NAME" value="VotingApp.driver.PopulateTestData$VotingAppMain" />
+      <module name="jpa-tutorial" />
+      <extension name="coverage">
+        <pattern>
+          <option name="PATTERN" value="VotingApp.driver.*" />
+          <option name="ENABLED" value="true" />
+        </pattern>
+      </extension>
+      <method v="2">
+        <option name="Make" enabled="true" />
+      </method>
+    </configuration>
+    <recent_temporary>
+      <list>
+        <item itemvalue="Application.PopulateTestData$VotingAppMain" />
+      </list>
+    </recent_temporary>
+  </component>
 </project>
\ No newline at end of file
Index: .idea/misc.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+><?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<project version=\"4\">\r\n  <component name=\"ExternalStorageConfigurationManager\" enabled=\"true\" />\r\n  <component name=\"MavenProjectsManager\">\r\n    <option name=\"originalFiles\">\r\n      <list>\r\n        <option value=\"$PROJECT_DIR$/pom.xml\" />\r\n      </list>\r\n    </option>\r\n  </component>\r\n  <component name=\"ProjectRootManager\" version=\"2\" languageLevel=\"JDK_17\" default=\"true\" project-jdk-name=\"17\" project-jdk-type=\"JavaSDK\" />\r\n</project>
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.idea/misc.xml b/.idea/misc.xml
--- a/.idea/misc.xml	(revision 27adf916a822967d46e2f667e4c1aad320e8d14e)
+++ b/.idea/misc.xml	(date 1696683058021)
@@ -1,4 +1,3 @@
-<?xml version="1.0" encoding="UTF-8"?>
 <project version="4">
   <component name="ExternalStorageConfigurationManager" enabled="true" />
   <component name="MavenProjectsManager">
Index: DB.trace.db
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>2023-09-16 14:40:45 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement \"\\000a    drop table if exists [*]User cascade \"; expected \"identifier\"; SQL statement:\r\n\r\n    drop table if exists User cascade  [42001-220]\r\n2023-09-16 14:40:45 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement \"\\000a    create table [*]User (\\000a        isAdmin boolean,\\000a        createdDate timestamp(6),\\000a        lastLoginDate timestamp(6),\\000a        userID bigint generated by default as identity,\\000a        email varchar(255),\\000a        name varchar(255),\\000a        password varchar(255),\\000a        primary key (userID)\\000a    )\"; expected \"identifier\"; SQL statement:\r\n\r\n    create table User (\r\n        isAdmin boolean,\r\n        createdDate timestamp(6),\r\n        lastLoginDate timestamp(6),\r\n        userID bigint generated by default as identity,\r\n        email varchar(255),\r\n        name varchar(255),\r\n        password varchar(255),\r\n        primary key (userID)\r\n    ) [42001-220]\r\n2023-09-16 14:40:45 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement \"\\000a    alter table if exists Poll \\000a       add constraint FK9xoytthue92qp2oel0kkgs0i8 \\000a       foreign key (created_by_user) \\000a       references [*]User\"; expected \"identifier\"; SQL statement:\r\n\r\n    alter table if exists Poll \r\n       add constraint FK9xoytthue92qp2oel0kkgs0i8 \r\n       foreign key (created_by_user) \r\n       references User [42001-220]\r\n2023-09-16 14:40:45 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement \"\\000a    alter table if exists Vote \\000a       add constraint FK78x2ik3lctm9na4o4c9fqmhdg \\000a       foreign key (user_id) \\000a       references [*]User\"; expected \"identifier\"; SQL statement:\r\n\r\n    alter table if exists Vote \r\n       add constraint FK78x2ik3lctm9na4o4c9fqmhdg \r\n       foreign key (user_id) \r\n       references User [42001-220]\r\n2023-09-16 14:40:45 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement \"insert into [*]User (createdDate,email,isAdmin,lastLoginDate,name,password,userID) values (?,?,?,?,?,?,default)\"; expected \"identifier\"; SQL statement:\r\ninsert into User (createdDate,email,isAdmin,lastLoginDate,name,password,userID) values (?,?,?,?,?,?,default) [42001-220]\r\n2023-09-16 14:42:20 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:42:20 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:42:20 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:42:20 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:44:35 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:45:32 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-16 14:46:37 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:48:53 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 14:49:40 database: flush\r\norg.h2.message.DbException: General error: \"org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.get(DbException.java:216)\r\n\tat org.h2.message.DbException.convert(DbException.java:414)\r\n\tat org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)\r\n\tat org.h2.mvstore.MVStore.handleException(MVStore.java:3296)\r\n\tat org.h2.mvstore.MVStore.panic(MVStore.java:585)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:461)\r\n\tat org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:129)\r\n\tat org.h2.engine.Database.<init>(Database.java:324)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:92)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:222)\r\n\tat org.h2.engine.Engine.createSession(Engine.java:201)\r\n\tat org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)\r\n\tat org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)\r\n\tat org.h2.Driver.connect(Driver.java:59)\r\n\tat com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:719)\r\n\tat com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:153)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)\r\n\tat java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:399)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: \"org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:573)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:496)\r\n\t... 34 more\r\nCaused by: org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\r\n\tat org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)\r\n\tat org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)\r\n\tat org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:875)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:455)\r\n\t... 28 more\r\n2023-09-18 14:49:40 database: opening C:/Users/magau/dat250/gruppe_prosjekt/dat250-echoP/DB\r\norg.h2.message.DbException: General error: \"The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.get(DbException.java:216)\r\n\tat org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:140)\r\n\tat org.h2.engine.Database.<init>(Database.java:324)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:92)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:222)\r\n\tat org.h2.engine.Engine.createSession(Engine.java:201)\r\n\tat org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)\r\n\tat org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)\r\n\tat org.h2.Driver.connect(Driver.java:59)\r\n\tat com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:719)\r\n\tat com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:153)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)\r\n\tat java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:399)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: \"The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:573)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:496)\r\n\t... 29 more\r\nCaused by: org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\r\n\tat org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)\r\n\tat org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)\r\n\tat org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:875)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:455)\r\n\tat org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:129)\r\n\t... 26 more\r\n2023-09-18 14:49:40 database: flush\r\norg.h2.message.DbException: General error: \"org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.get(DbException.java:216)\r\n\tat org.h2.message.DbException.convert(DbException.java:414)\r\n\tat org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)\r\n\tat org.h2.mvstore.MVStore.handleException(MVStore.java:3296)\r\n\tat org.h2.mvstore.MVStore.panic(MVStore.java:585)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:461)\r\n\tat org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:129)\r\n\tat org.h2.engine.Database.<init>(Database.java:324)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:92)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:222)\r\n\tat org.h2.engine.Engine.createSession(Engine.java:201)\r\n\tat org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)\r\n\tat org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)\r\n\tat org.h2.Driver.connect(Driver.java:59)\r\n\tat com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:719)\r\n\tat com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:153)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)\r\n\tat java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:399)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: \"org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:573)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:496)\r\n\t... 34 more\r\nCaused by: org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\r\n\tat org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)\r\n\tat org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)\r\n\tat org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:875)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:455)\r\n\t... 28 more\r\n2023-09-18 14:49:40 database: opening C:/Users/magau/dat250/gruppe_prosjekt/dat250-echoP/DB\r\norg.h2.message.DbException: General error: \"The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.get(DbException.java:216)\r\n\tat org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:140)\r\n\tat org.h2.engine.Database.<init>(Database.java:324)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:92)\r\n\tat org.h2.engine.Engine.openSession(Engine.java:222)\r\n\tat org.h2.engine.Engine.createSession(Engine.java:201)\r\n\tat org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)\r\n\tat org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)\r\n\tat org.h2.Driver.connect(Driver.java:59)\r\n\tat com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.connect(JdbcHelperImpl.java:719)\r\n\tat com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:153)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)\r\n\tat java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:712)\r\n\tat java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)\r\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:399)\r\n\tat java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\r\n\tat java.base/java.lang.Thread.run(Thread.java:833)\r\nCaused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: \"The write format 3 is larger than the supported format 2 [2.1.210/5]\" [50000-210]\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:573)\r\n\tat org.h2.message.DbException.getJdbcSQLException(DbException.java:496)\r\n\t... 29 more\r\nCaused by: org.h2.mvstore.MVStoreException: The write format 3 is larger than the supported format 2 [2.1.210/5]\r\n\tat org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)\r\n\tat org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1059)\r\n\tat org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:875)\r\n\tat org.h2.mvstore.MVStore.<init>(MVStore.java:455)\r\n\tat org.h2.mvstore.MVStore$Builder.open(MVStore.java:4056)\r\n\tat org.h2.mvstore.db.Store.<init>(Store.java:129)\r\n\t... 26 more\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 16:49:56 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:46:11 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:53:44 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 17:56:59 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n2023-09-18 18:05:24 jdbc[3]: exception\r\norg.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]\r\n
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/DB.trace.db b/DB.trace.db
--- a/DB.trace.db	(revision 27adf916a822967d46e2f667e4c1aad320e8d14e)
+++ b/DB.trace.db	(date 1696683088690)
@@ -510,3 +510,39 @@
 org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
 2023-09-18 18:05:24 jdbc[3]: exception
 org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
+2023-10-07 14:51:28 jdbc[3]: exception
+org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-220]
